project_id = "cshoskwtvjhlwgxntjzs"

[functions.process-scheduled-campaigns]
verify_jwt = false

[functions.register-subscriber]
verify_jwt = false

[functions.track-notification]
verify_jwt = false

[functions.send-test-notification]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = true
